# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160330_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['article', 'date_posted']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_text']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
