# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160331_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag_count',
        ),
    ]
