# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160401_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
