# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160401_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
