# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160401_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_posted']},
        ),
    ]
