# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 02:02
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20160405_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
