# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20160406_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
