# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20160407_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
